// Mock data for demo purposes

export const mockInfluencers = [
    {
        id: 'inf1',
        userId: 'user_inf1',
        name: 'Priya Sharma',
        email: 'priya@example.com',
        city: 'Delhi',
        area: 'Connaught Place',
        category: 'Food',
        followers: 12500,
        avgLikes: 850,
        engagementRate: 6.8,
        pricePerPost: 4500,
        verified: true,
        bio: 'Food blogger exploring Delhi\'s culinary scene 🍕',
        portfolio: ['instagram.com/priya_foodie'],
    },
    {
        id: 'inf2',
        userId: 'user_inf2',
        name: 'Rahul Verma',
        email: 'rahul@example.com',
        city: 'Mumbai',
        area: 'Bandra',
        category: 'Fitness',
        followers: 18000,
        avgLikes: 1200,
        engagementRate: 6.7,
        pricePerPost: 6000,
        verified: true,
        bio: 'Fitness coach helping you achieve your goals 💪',
        portfolio: ['instagram.com/rahul_fit'],
    },
    {
        id: 'inf3',
        userId: 'user_inf3',
        name: 'Sneha Patel',
        email: 'sneha@example.com',
        city: 'Delhi',
        area: 'Lajpat Nagar',
        category: 'Fashion',
        followers: 22000,
        avgLikes: 1500,
        engagementRate: 6.8,
        pricePerPost: 7000,
        verified: true,
        bio: 'Fashion stylist & content creator ✨',
        portfolio: ['instagram.com/sneha_style'],
    },
    {
        id: 'inf4',
        userId: 'user_inf4',
        name: 'Amit Kumar',
        email: 'amit@example.com',
        city: 'Bangalore',
        area: 'Koramangala',
        category: 'Technology',
        followers: 15000,
        avgLikes: 900,
        engagementRate: 6.0,
        pricePerPost: 5500,
        verified: true,
        bio: 'Tech reviewer & gadget enthusiast 📱',
        portfolio: ['instagram.com/amit_tech'],
    },
    {
        id: 'inf5',
        userId: 'user_inf5',
        name: 'Neha Singh',
        email: 'neha@example.com',
        city: 'Delhi',
        area: 'Karol Bagh',
        category: 'Food',
        followers: 10000,
        avgLikes: 650,
        engagementRate: 6.5,
        pricePerPost: 3500,
        verified: false,
        bio: 'Home chef & recipe creator 🍳',
        portfolio: ['instagram.com/neha_cooks'],
    },
    {
        id: 'inf6',
        userId: 'user_inf6',
        name: 'Vikram Mehta',
        email: 'vikram@example.com',
        city: 'Mumbai',
        area: 'Andheri',
        category: 'Travel',
        followers: 25000,
        avgLikes: 1800,
        engagementRate: 7.2,
        pricePerPost: 8000,
        verified: true,
        bio: 'Travel vlogger exploring India 🌍',
        portfolio: ['instagram.com/vikram_travels'],
    },
    {
        id: 'inf7',
        userId: 'user_inf7',
        name: 'Anjali Reddy',
        email: 'anjali@example.com',
        city: 'Hyderabad',
        area: 'Banjara Hills',
        category: 'Beauty',
        followers: 20000,
        avgLikes: 1400,
        engagementRate: 7.0,
        pricePerPost: 6500,
        verified: true,
        bio: 'Makeup artist & beauty influencer 💄',
        portfolio: ['instagram.com/anjali_beauty'],
    },
    {
        id: 'inf8',
        userId: 'user_inf8',
        name: 'Rohan Kapoor',
        email: 'rohan@example.com',
        city: 'Delhi',
        area: 'Nehru Place',
        category: 'Fitness',
        followers: 14000,
        avgLikes: 920,
        engagementRate: 6.6,
        pricePerPost: 5000,
        verified: true,
        bio: 'Personal trainer & nutrition expert 🏋️',
        portfolio: ['instagram.com/rohan_fitness'],
    },
    {
        id: 'inf9',
        userId: 'user_inf9',
        name: 'Kavya Nair',
        email: 'kavya@example.com',
        city: 'Pune',
        area: 'Koregaon Park',
        category: 'Lifestyle',
        followers: 16000,
        avgLikes: 1050,
        engagementRate: 6.6,
        pricePerPost: 5500,
        verified: false,
        bio: 'Lifestyle blogger & mom influencer 👪',
        portfolio: ['instagram.com/kavya_life'],
    },
    {
        id: 'inf10',
        userId: 'user_inf10',
        name: 'Arjun Bhatt',
        email: 'arjun@example.com',
        city: 'Delhi',
        area: 'Saket',
        category: 'Food',
        followers: 11000,
        avgLikes: 720,
        engagementRate: 6.5,
        pricePerPost: 4000,
        verified: true,
        bio: 'Food critic & restaurant reviewer 🍴',
        portfolio: ['instagram.com/arjun_eats'],
    },
    {
        id: 'inf11',
        userId: 'user_inf11',
        name: 'Isha Gupta',
        email: 'isha@example.com',
        city: 'Mumbai',
        area: 'Powai',
        category: 'Fashion',
        followers: 19000,
        avgLikes: 1300,
        engagementRate: 6.8,
        pricePerPost: 6500,
        verified: true,
        bio: 'Fashion designer & style influencer 👗',
        portfolio: ['instagram.com/isha_fashion'],
    },
    {
        id: 'inf12',
        userId: 'user_inf12',
        name: 'Siddharth Joshi',
        email: 'sid@example.com',
        city: 'Bangalore',
        area: 'Indiranagar',
        category: 'Technology',
        followers: 13000,
        avgLikes: 850,
        engagementRate: 6.5,
        pricePerPost: 4800,
        verified: false,
        bio: 'Software engineer & tech content creator 💻',
        portfolio: ['instagram.com/sid_codes'],
    },
    {
        id: 'inf13',
        userId: 'user_inf13',
        name: 'Meera Shah',
        email: 'meera@example.com',
        city: 'Delhi',
        area: 'Rajouri Garden',
        category: 'Beauty',
        followers: 17000,
        avgLikes: 1150,
        engagementRate: 6.8,
        pricePerPost: 5800,
        verified: true,
        bio: 'Skincare enthusiast & beauty blogger ✨',
        portfolio: ['instagram.com/meera_glow'],
    },
    {
        id: 'inf14',
        userId: 'user_inf14',
        name: 'Karan Malhotra',
        email: 'karan@example.com',
        city: 'Chennai',
        area: 'T Nagar',
        category: 'Fitness',
        followers: 21000,
        avgLikes: 1450,
        engagementRate: 6.9,
        pricePerPost: 7000,
        verified: true,
        bio: 'Yoga instructor & wellness coach 🧘',
        portfolio: ['instagram.com/karan_yoga'],
    },
    {
        id: 'inf15',
        userId: 'user_inf15',
        name: 'Divya Iyer',
        email: 'divya@example.com',
        city: 'Delhi',
        area: 'Dwarka',
        category: 'Food',
        followers: 9500,
        avgLikes: 600,
        engagementRate: 6.3,
        pricePerPost: 3200,
        verified: false,
        bio: 'Baking enthusiast & dessert creator 🧁',
        portfolio: ['instagram.com/divya_bakes'],
    },
];

export const mockShops = [
    {
        id: 'shop1',
        userId: 'user_shop1',
        businessName: 'The Coffee Hub',
        email: 'coffee@example.com',
        city: 'Delhi',
        area: 'Connaught Place',
        category: 'Food',
        marketingBudget: 15000,
        subscriptionStatus: true,
        description: 'Premium coffee shop in the heart of Delhi',
    },
    {
        id: 'shop2',
        userId: 'user_shop2',
        businessName: 'FitZone Gym',
        email: 'fitzone@example.com',
        city: 'Mumbai',
        area: 'Bandra',
        category: 'Fitness',
        marketingBudget: 25000,
        subscriptionStatus: true,
        description: 'State-of-the-art fitness center',
    },
    {
        id: 'shop3',
        userId: 'user_shop3',
        businessName: 'Trendy Boutique',
        email: 'trendy@example.com',
        city: 'Delhi',
        area: 'Lajpat Nagar',
        category: 'Fashion',
        marketingBudget: 20000,
        subscriptionStatus: true,
        description: 'Latest fashion trends and designer wear',
    },
    {
        id: 'shop4',
        userId: 'user_shop4',
        businessName: 'Spice Garden',
        email: 'spice@example.com',
        city: 'Delhi',
        area: 'Karol Bagh',
        category: 'Food',
        marketingBudget: 12000,
        subscriptionStatus: false,
        description: 'Authentic Indian cuisine restaurant',
    },
    {
        id: 'shop5',
        userId: 'user_shop5',
        businessName: 'Tech Store',
        email: 'techstore@example.com',
        city: 'Bangalore',
        area: 'Koramangala',
        category: 'Technology',
        marketingBudget: 30000,
        subscriptionStatus: true,
        description: 'Latest gadgets and electronics',
    },
    {
        id: 'shop6',
        userId: 'user_shop6',
        businessName: 'Glow Beauty Salon',
        email: 'glow@example.com',
        city: 'Delhi',
        area: 'Rajouri Garden',
        category: 'Beauty',
        marketingBudget: 18000,
        subscriptionStatus: true,
        description: 'Premium beauty and spa services',
    },
    {
        id: 'shop7',
        userId: 'user_shop7',
        businessName: 'Yoga Retreat',
        email: 'yoga@example.com',
        city: 'Delhi',
        area: 'Saket',
        category: 'Fitness',
        marketingBudget: 15000,
        subscriptionStatus: false,
        description: 'Holistic wellness and yoga center',
    },
    {
        id: 'shop8',
        userId: 'user_shop8',
        businessName: 'Pasta Paradise',
        email: 'pasta@example.com',
        city: 'Mumbai',
        area: 'Powai',
        category: 'Food',
        marketingBudget: 16000,
        subscriptionStatus: true,
        description: 'Italian restaurant with authentic flavors',
    },
];

export const mockCollaborations = [
    {
        id: 'collab1',
        shopId: 'shop1',
        influencerId: 'inf1',
        status: 'accepted',
        createdAt: new Date('2024-02-10').toISOString(),
    },
    {
        id: 'collab2',
        shopId: 'shop2',
        influencerId: 'inf2',
        status: 'pending',
        createdAt: new Date('2024-02-14').toISOString(),
    },
    {
        id: 'collab3',
        shopId: 'shop3',
        influencerId: 'inf3',
        status: 'completed',
        createdAt: new Date('2024-01-20').toISOString(),
    },
];

export const mockMessages = [
    {
        id: 'msg1',
        senderId: 'user_shop1',
        receiverId: 'user_inf1',
        text: 'Hi Priya! We loved your food content. Would love to collaborate!',
        timestamp: new Date('2024-02-10T10:00:00').toISOString(),
    },
    {
        id: 'msg2',
        senderId: 'user_inf1',
        receiverId: 'user_shop1',
        text: 'Thanks! I\'d be happy to feature The Coffee Hub. Let\'s discuss the details.',
        timestamp: new Date('2024-02-10T10:30:00').toISOString(),
    },
    {
        id: 'msg3',
        senderId: 'user_shop1',
        receiverId: 'user_inf1',
        text: 'Perfect! We can offer you a complimentary tasting session. When are you available?',
        timestamp: new Date('2024-02-10T11:00:00').toISOString(),
    },
];
